name: Release Log

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Read RELEASE.md
        run: |
          TODAY=$(date '+%Y-%m-%d')

          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV

          echo -e "\`$TODAY\`\n" >> $GITHUB_ENV

          cat RELEASE.md >> $GITHUB_ENV

          echo "EOF" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
