name: Release Log

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Read RELEASE.md
        run: |
          TODAY=$(date '+%Y-%m-%d')

          FILE_CONTENT=$(cat RELEASE.md)
          
          RELEASE_BODY="${TODAY}\n${FILE_CONTENT}"
          
          echo -e "RELEASE_BODY=${RELEASE_BODY}" >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
